# Generated by Django 2.1.3 on 2018-11-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('doc_pk', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='upload.Document/bytes/filename/mimetype')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_pk', models.AutoField(primary_key=True, serialize=False)),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
    ]
